export const expenseCategoryIconKeys = [
  "food",
  "home",
  "card",
  "car",
  "health",
  "medicine",
  "education",
  "subscription",
  "water",
  "energy",
  "phone",
  "tv",
  "insurance",
  "gym",
  "investment",
  "money",
  "shopping",
  "leisure",
  "domestic",
  "pet",
  "travel",
  "gift",
  "family",
  "work",
  "bill",
  "other",
] as const;

export type ExpenseCategoryIconKey = (typeof expenseCategoryIconKeys)[number];

export const expenseCategoryIconLabels: Record<ExpenseCategoryIconKey, string> =
  {
    food: "Alimentação",
    home: "Moradia",
    card: "Cartão",
    car: "Transporte",
    health: "Saúde",
    medicine: "Medicamentos",
    education: "Educação",
    subscription: "Assinaturas",
    water: "Água",
    energy: "Energia",
    phone: "Telefonia",
    tv: "TV e internet",
    insurance: "Seguros",
    gym: "Academia",
    investment: "Investimentos",
    money: "Dinheiro",
    shopping: "Compras",
    leisure: "Lazer",
    domestic: "Doméstica",
    pet: "Pets",
    travel: "Viagens",
    gift: "Presentes",
    family: "Família",
    work: "Trabalho",
    bill: "Conta",
    other: "Outros",
  };
